export const APP_NAVIGATOR = 'APP';
export const AUTH_NAVIGATOR = 'AUTH';
export const HOME_SCREEN = 'HOME_SCREEN';
export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const ROOM_LIST_SCREEN = 'ROOM_LIST_SCREEN';
export const ROOM_HISTORY_SCREEN = 'ROOM_HISTORY_SCREEN';
export const NEW_ROOM_SCREEN = 'NEW_ROOM_SCREEN';
