export const HOME_SCREEN = 'HOME_SCREEN';
export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const REGISTER_SCREEN = 'REGISTER_SCREEN';
export const ROOM_LIST_SCREEN = 'ROOM_LIST_SCREEN';
export const ROOM_HISTORY_SCREEN = 'ROOM_HISTORY_SCREEN';
